import { User } from "./User";

export let profileDetail: User[] = [
    {
        id: 1,
        firstName: "Abdullah Rafi",
        designation: "Software Engineer",
        email: "abdullah.rafi@example.com",
        contactNumber: "+1234567890",
        degree1: "Bachelor of Science in Computer Science",
        passingYear1: 2018,
        institution1: "University of Example",
        degree2: "Bachelor of Science in Computer Science",
        passingYear2: 2018,
        institution2: "University of Example",
        skills: "JavaScript, Angular, Node.js, MongoDB",
        jobTitle1: "Full Stack Developer",
        jobQuitYear1: 2022,
        description: "Passionate about creating scalable and efficient web applications.",
        jobTitle2: "Full Stack Developer",
        jobQuitYear2: 2022,
        jobDescription1: "Worked on developing and maintaining various web applications using Angular and Node.js.",
        jobDescription2: "Worked on developing and maintaining various web applications using Angular and Node.js.",
        referrerName1: "John Doe",
        referrerEmail1: "john.doe@example.com",
        referrerNo1: "+9876543210",
        referrerName2: "John Doe",
        referrerEmail2: "john.doe@example.com",
        referrerNo2: "+9876543210"
    },
    {
        id: 2,
        firstName: "Shobuj Mia",
        designation: "Graphic Designer",
        email: "shobuj.mia@example.com",
        contactNumber: "+9876543210",
        degree1: "Bachelor of Fine Arts in Graphic Design",
        passingYear1: 2019,
        institution1: "Art Institute of Example",
        skills: "Adobe Photoshop, Illustrator, InDesign",
        jobTitle1: "Senior Graphic Designer",
        jobQuitYear1: 2023,
        description: "Creative and detail-oriented graphic designer with a passion for visual storytelling.",
        jobDescription1: "Led a team of designers to create compelling visual assets for marketing campaigns.",
        referrerName1: "Jane Smith",
        referrerEmail1: "jane.smith@example.com",
        referrerNo1: "+1234509876"
    },
    {
        id: 3,
        firstName: "Mamun Mia",
        designation: "Data Analyst",
        email: "mamun.mia@example.com",
        contactNumber: "+1122334455",
        degree1: "Bachelor of Science in Statistics",
        passingYear1: 2017,
        institution1: "Statistics University",
        skills: "SQL, Python, Tableau",
        jobTitle1: "Data Analyst",
        jobQuitYear1: 2021,
        description: "Detail-oriented data analyst with a passion for uncovering insights from data.",
        jobDescription1: "Analyzed large datasets to identify trends and patterns for business decision-making.",
        referrerName1: "Sarah Johnson",
        referrerEmail1: "sarah.johnson@example.com",
        referrerNo1: "+1122334455"
    }
];
